add_compile_definitions(DEBUG=$<CONFIG:Debug>)

add_compile_definitions(CLANG=$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>>)
add_compile_definitions(GNUC=$<CXX_COMPILER_ID:GNU>)
add_compile_definitions(MSVC=$<CXX_COMPILER_ID:MSVC>)
add_compile_definitions(APPLE_CLANG=$<CXX_COMPILER_ID:AppleClang>)

add_compile_definitions(PLATFORM_WINDOWS=$<PLATFORM_ID:Windows>)
add_compile_definitions(PLATFORM_MACOS=$<PLATFORM_ID:Darwin>)
add_compile_definitions(PLATFORM_LINUX=$<PLATFORM_ID:Linux>)

if (MSVC)
    add_compile_definitions(_ALLOW_KEYWORD_MACROS)
    add_compile_definitions("CHAR_T=wchar_t")
    add_compile_definitions("force_inline=msvc::forceinline")
    #add_compile_definitions("inline=msvc::noinline")
    add_compile_definitions("no_unique_address=msvc::no_unique_address")
else()
    add_compile_definitions("force_inline=gnu::always_inline")
    add_compile_definitions("noinline=gnu:noinline")
endif()